from . import tic_tac_toe
from . import rock_paper_scissors
from . import number_guessing
from . import hangman
from . import math_quiz
from . import typing_challenge
from . import connect4
from . import memory_match
from . import word_chain
from . import flag_guess
from . import country_capital
